name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*" # Se ejecuta cuando hay un push con tags semánticos como v1.0.0
    branches:
      - "main"   # Opcional: También puede ejecutarse en la rama main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout del repositorio
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Obtener el tag del commit actual
    - name: Get the current tag
      id: versioning
      run: |
        # Obtener el tag actual asociado al commit
        TAG=$(git describe --tags --exact-match 2>/dev/null || echo "no-tag")
        if [ "$TAG" = "no-tag" ]; then
          echo "Error: Este commit no tiene un tag asociado. Por favor, etiqueta el commit antes de continuar."
          exit 1
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "El tag actual es: $TAG"

    # 3. Login en Docker
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login…."
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"

    # 4. Construir y etiquetar la imagen Docker
    - name: Build and tag Docker image
      run: |
        docker build -t esrora/docker-prueba:${{ env.TAG }} .
        docker build -t esrora/docker-prueba:latest .
        docker push esrora/docker-prueba:${{ env.TAG }}
        docker push esrora/docker-prueba:latest
