name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: ${major}.${minor}.${patch}
      id: version
      
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Nueva Version: $NEW_VERSION !!!!!!!"
        
    - name: Build Docker Image
      run: |
        docker image build -t esrora/docker-prueba:0.0.2 .
        docker image build -t esrora/docker-prueba:latest .
    - name: Push Docker Image
      run: |
        docker image push esrora/docker-prueba:0.0.2
        docker image push esrora/docker-prueba:latest
