name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Increment version
      id: version
      uses: RichardInnocent/semantic-versioning-git@v0.0.1
    
    - name: Print if version changed
      if: steps.increment-version.outputs.previous-version != steps.increment-version.outputs.new-version
      run: echo "The new version is now $new_version"
      env:
        new_version: ${{ steps.increment-version.outputs.new-version }}

#    - name: Docker login
#      env:
#        DOCKER_USER: ${{ secrets.DOCKER_USER }}
#        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#      run: |
#        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#        echo ${{ steps.version.outputs.version }}
        
#    - name: Build Docker Image
#      env:
#        NEW_VERSION: ${{ steps.version.outputs.version }}
#      run: |
#        docker image build -t esrora/docker-prueba:$NEW_VERSION .
#        docker image build -t esrora/docker-prueba:latest .
#    - name: Push Docker Image
#      env:
#        NEW_VERSION: ${{ steps.version.outputs.version }}
#      run: |
#        docker image push esrora/docker-prueba:$NEW_VERSION
#        docker image push esrora/docker-prueba:latest
